spring:
  application:
    name: toDoApp
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/todoapp
    username: postgres
    password: 2810
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  authentication:
    jwt:
      expiration-in-ms: 86400000 # 24 hours
      refresh-token-expiration-in-ms: 259200000 # 3 days
      private-key: "MIIEpAIBAAKCAQEAivwHnvcCURwSqYhiKenGMuVWNdgrsiSoCHEG5K1mFUk3B/+pq1djEfi5sd8Z/1m/+4NReFDVhicIHU1KTJQj3/KwQEGCPgXBQ/K/OkiAjy8xvGXGqKHmp5aNpGWO69HA5wExz3VQhau2XKALo8af/M7ZxqcGqM+qX0BspB1k3Z5h1SAIbJQNiWlrxx94ZRS+yVXdYiNvwIkpW2989wVL8pFchcAzdAWWXzRiNhGbM9IWSFmjjB2XD53UnYZkP+wubbZupTOzKupljYf/2yD5j3TtFnKqSt3dTH3gLImX+CmBuCKK7PVJeVu7gfQaCYR0ejrbtiazc9pc/1Q9+OxrVQIDAQABAoIBACNX+DAqrIIn228VabEy694hiAzlTiddPwX2iEQ6/EzJc58rGuChtmXplH9xNtFC55l0SZGJLOOSpXOeJhjXS1A2DTAp+I8BM6at4odVzKuc2s8IKr7TfS59EMQPt4qsqpuUKDCTqshzZEqlwJADgMfval4kN4NSXAchAP+zIeVhclKe7qbFaSpR4cTCjIwqMiy+Fs/p05er0wlom9723bJX37w2mQs9PZJBmyVWd3zBg3G9lpbR299jWWdwJvnLDdDif1/6zvqUj8ul2Rz85zGlDvBnXZlPrylwp/hBOc8bhHeyn+3ynCGuGNLNupByc1qce6K7w6qmPwb+mLY9w3kCgYEA3iRzxi82bD+HsXI9oJlreoCuhmQRIolRbB8k0rXEpcaGtVZ87/B7Sr1zH9w0yxax64EhW3hR/ubrKvhmtAwUvM3GmvF/j0dHZyS4ukPn+pmNooaUTGZUe6GcmaWuOSb30j/q29xBO8SFeHihoMeEzFy4scOgzhZ3zgICywL0IT8CgYEAoCrskcgSNdxQUqsUwjfhc11yqOUtb6GVZbj2vuf3H4CX0N86lL5GW7zNX147HUwk/L0Q5FG475povDghtaQYs6VHCmDgXTGVYOYBDyuq2JTSDc28iutt4PWBMEVHifHUk27kZ4G37Fa0H3KIrPV8udM6HmiAc8BW47MZ+JXV+msCgYEAruigyAFQprb3Dr7Wy2dBezlrMaIE496fX7S997LrXWQNmSa6ROpjCZxV01Y9s1LxUG9iZnU8iqojrLfdlhKVGXwkzscsGxKSpCID2ZWySF0zai7xAZ7pEldTyJ7tqU6HfuKY9/ha3MaGGS9ShBfU9lxjiIRyTxLdzjVDIbn3o10CgYEAkLv5JwtamV1LIEkE6zTAABYTxNfEJToo3NE19/F5+PelONRgBYWj4sZL98AZPzJNwi2/k/LdYXdw6ZT3sUJmKABUn+ZHGS/zQqrVjjXxnuFsp5igphB1LHHtmgcgzGDBrbDpqTcpUuJOxpQjOdhkKy/bNxtL6E2Itx5je6U6xZ0CgYBZRiayYr91g0YRbRQau0eh5jnQweECvCi5cv0fIMvT7y7mjQwUJFhah8APSlYVqF86QTsrxqjNzUwMmp6fmfWWwd1MMmGAn72+Zx93BzOO2drDG7CSx9p7RJv8Nt3+YyBSeQ1XNEAw+GMP6Ro+4PwRJ/GsXltGTQNapQNw/DBpsw=="
      public-key: "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAivwHnvcCURwSqYhiKenGMuVWNdgrsiSoCHEG5K1mFUk3B/+pq1djEfi5sd8Z/1m/+4NReFDVhicIHU1KTJQj3/KwQEGCPgXBQ/K/OkiAjy8xvGXGqKHmp5aNpGWO69HA5wExz3VQhau2XKALo8af/M7ZxqcGqM+qX0BspB1k3Z5h1SAIbJQNiWlrxx94ZRS+yVXdYiNvwIkpW2989wVL8pFchcAzdAWWXzRiNhGbM9IWSFmjjB2XD53UnYZkP+wubbZupTOzKupljYf/2yD5j3TtFnKqSt3dTH3gLImX+CmBuCKK7PVJeVu7gfQaCYR0ejrbtiazc9pc/1Q9+OxrVQIDAQAB"
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
  mail:
    host: smtp.gmail.com
    port: 587
    username: test-email@gmail.com
    password: test-email-password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
