spring:
  application:
    name: toDoApp
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/todoapp
    username: postgres
    password: 2810
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  authentication:
    jwt:
      expiration-in-ms: 86400000 # 24 hours
      refresh-token-expiration-in-ms: 259200000 # 3 days
      private-key: "<your-private-key>"
      public-key: "<your-public-key>"
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
  mail:
    host: smtp.gmail.com
    port: 587
    username: test-email@gmail.com
    password: test-email-password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
